### ISSUE TITLE
Issues Update 17/06

### ISSUE THREAD

**Issue by stp14-z** [MineCronik/MaxxOS#3]
Hi MaxxOS Team,
I have a few issues relate to your website (http://www.maxx.run).
Issue 1: Some links via "Friendly Links" were not working, they are listed below:

**XiangWu Blog (http://www.maxx.run/xwblog/index.html)**
**CronikMC Server (http://www.maxx.run/cronikmc)**

Issue 2: Studio Joining Application is refusing to download. (http://www.maxx.run/join/downloads/MaxxOS_ShenHe.exe) Windows has scanned it as resulted virus included. I have reported this to Microsoft as a safe application, however, in order to make sure it is safe to download, please go to **https://fb.smartscreen.microsoft.com/feedback.aspx** and press the second button: **I am the owner or representative of this website and I want to report an incorrect warning about it** and follow the guideline to fix the incorrect warning of your application.

For any further enquiry about this update, please contact +61 460615566 or zho0014@cheltsec.vic.edu.au.
Yours Sincerely
Xiaoran Zhou [Shawn]
17/06/2020

**Comment by MineCronik** [comment]
Hello,Thank you for your report.
Our Maxx website was originally run in xwblogger server. Due to the website migration(to maxx.run), some bugs have not been fixed.
Our Maxx Joining Application has been checked by Huorong, 360 and Avast, and all anti-virus software shows no problem. (probably because of the use of Yi language)
